# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentacajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.CharField(max_length=2)),
                ('Mat_Caja', models.CharField(max_length=4)),
                ('cant', models.IntegerField(default=12345)),
                ('zona', models.IntegerField(default=125)),
                ('revend', models.IntegerField(default=1400222)),
                ('HoraAct', models.TimeField(default=datetime.datetime(2017, 11, 27, 10, 17, 32, 735399))),
            ],
        ),
    ]
